name: Congrats!
run-name: Congrats!
on: 
    pull_request: 
        types: [ closed ]

jobs:
    comment:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Greetings
              uses: actions/github-script@v5
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    OWNER=github.event.pull_request.head.repo.owner.login
                    BODY="Congrats @$OWNER! You're project has just been merged!\n\nYour next step is to claim your grant! You should have just received an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!\n\nIf you have any questions, feel free to reach out in [`#onboard-help`](https://hackclub.slack.com/archives/C0593MG26TT) or to contact @daisy from bank.\n\nNow, you can finally get those PCBs ordered!ðŸŽ‰\n\nP.S. If you haven't already, join the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ)channel. There's a party brewing!"

                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: $BODY
                    })
# body: "Congrats! You're project has been merged! Your next step is to schedule a call with @daisy (from Bank) to get setup with your OnBoard card! Find a time [here](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ0pvZ17vB492hU6bVBAFJsYgILdPQr32t5z4LrC7DWHfJDMLGs3A0ca-OfvZe3h6I6FmIuom6mM)"