name: PR Greeter
run-name: PR Greeter
on:
    pull_request:
        types: [ opened ]

permissions:
    pull-requests: write
    issues: write

jobs:
    Greetings:
        runs-on: ubuntu-latest
        steps:
            - name: Assign to reviewers
              uses: madrapps/add-reviewers@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                reviewers: 'bykevinyang'
                re-request-when-changes-requested: true
                re-request-when-approved: true

            - name: Label as submission
              uses: actions/github-script@v5
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.rest.issues.addLabels({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        labels: ['Submission']
                    })
            
            - name: Greetings
              uses: thollander/actions-comment-pull-request@v2.3.1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                message: |
                    ![Orpheus waving](http://rawr.hackclub.com/hyper-dino-wave.gif)
                    
                    ðŸ‘‹ **Hey there!** Welcome to [OnBoard](https://onboard.hackclub.com/)! We got your submission! We currently have our best and brightest reviewing this PR!
                    
                    In the meantime, hang out in [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ). People are making some really cool stuff!
                    
                    I'll see you in a bit! Woo!
                
            # - name: Greetings
            #   uses: actions/github-script@v5
            #   env:
            #     GITHUB_URL: ${{ github.event.pull_request.comments_url }}
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   with:
            #     script: |
            #         echo "test"