name: PR Greeter
run-name: PR Greeter
on:
    pull_request:
        types: [ opened ]

jobs:
    Greetings:
        runs-on: ubuntu-latest
        steps:

            - name: Assign to reviewers
              uses: actions/github-script@v5
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.rest.issues.addAssignees({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        assignees: ['bykevinyang']
                    })

            - name: Label as submission
              uses: actions/github-script@v5
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.rest.issues.addLabels({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        labels: ['Submission']
                    })
             
            - name: Greetings
              uses: actions/github-script@v5
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
                    PR_URL="https://github.com/hackclub/OnBoard/pull/${PR_NUMBER}"
                    echo "${PR_URL}"

                    GITHUB_HANDLE=context.payload.pull_request.user.login
                    echo "${GITHUB_HANDLE}"

                    URL="https://airtable.com/shrRaW9OXoIwUXn1E?prefill_PR=${PR_URL}&hide_PR=true&prefill_Github+Handle=${GITHUB_HANDLE}&hide_Github+Handle=true"
                    echo "${URL}"

                    BODY="![Orpheus waving](http://rawr.hackclub.com/hyper-dino-wave.gif)\n\nðŸ‘‹ Hey there! Welcome to [OnBoard](https://onboard.hackclub.com/)! We got your submission! We currently have our best and brightest reviewing this PR!\n\nIn the meantime, we'll need your email and photo ID to set you setup with Hack Club Bank! **Can you fill out this [form](${URL})**?\n\nSee you in a bit! Woo!"
                    echo "${BODY}"