name: PR Greeter
run-name: PR Greeter

on:
    pull_request:
        branches:
            - main
        types: [ opened ]

jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - name: Greetings
              uses: actions/github-script@v5
              with:
                # github-token: ${{secrets.ONBRDER_TOKEN}}
                script: |
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: "
                        ðŸ‘‹ Hey there! We got your merge! @bykevinyang will be reviewing it very soon. Check back in 24 hours for an update!\n
                        
                        Get ready!
                        "
                    })
             
            - name: Assign to reviewers
              uses: actions/github-script@v5
              with:
                # github-token: ${{secrets.ONBRDER_TOKEN}}
                script: |
                    github.rest.issues.addAssignees({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        assignees: ['bykevinyang']
                    })